import { constants } from "node:fs";
import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { stdin as defaultInput, stdout as defaultOutput } from "node:process";
import type { ReadStream, WriteStream } from "node:tty";
import { TestSpecError } from "../core/errors.js";
import { ARCHIVE_DIR, CHANGES_DIR, WORKSPACE_ROOT } from "../workflow/workspace.js";

export const GENERATED_FILE_MARKER =
  "<!-- Generated by TestSpec. Keep this marker to allow `testspec init` to refresh this file. -->";
export const AGENTS_SECTION_START = "<!-- BEGIN TESTSPEC AGENT WORKFLOW -->";
export const AGENTS_SECTION_END = "<!-- END TESTSPEC AGENT WORKFLOW -->";

export const WORKFLOW_COMMANDS = [
  {
    id: "new",
    label: "test:new",
    slashCommand: "/test:new",
    backingCommand: "testspec new <name> --requirement <path>",
    description: "Create a test proposal workspace from a requirement document.",
  },
  {
    id: "analysis",
    label: "test:analysis",
    slashCommand: "/test:analysis",
    backingCommand: "testspec analysis [name]",
    description: "Decompose requirements into testable items, risks, and questions.",
  },
  {
    id: "points",
    label: "test:points",
    slashCommand: "/test:points",
    backingCommand: "testspec points [name]",
    description: "Generate core scenario test points for a test change.",
  },
  {
    id: "validate",
    label: "test:validate",
    slashCommand: "/test:validate",
    backingCommand: "testspec validate [name]",
    description: "Validate generated workflow artifacts.",
  },
  {
    id: "excel",
    label: "test:excel",
    slashCommand: "/test:excel",
    backingCommand: "testspec excel [name]",
    description: "Export executable Excel test cases.",
  },
  {
    id: "mind",
    label: "test:mind",
    slashCommand: "/test:mind",
    backingCommand: "testspec mind [name]",
    description: "Export mind-map style test cases for review.",
  },
  {
    id: "report",
    label: "test:report",
    slashCommand: "/test:report",
    backingCommand: "testspec report [name]",
    description: "Generate execution statistics from Excel results.",
  },
  {
    id: "archive",
    label: "test:archive",
    slashCommand: "/test:archive",
    backingCommand: "testspec archive [name]",
    description: "Archive the full test artifact chain for traceability.",
  },
] as const;

export type WorkflowCommand = (typeof WORKFLOW_COMMANDS)[number];
export type AgentId = "claude" | "qoder" | "codex" | "generic";

export const PROVIDER_NEUTRAL_PROMPT_RULES = [
  "The coding agent performs semantic generation; the TestSpec CLI remains provider-free and deterministic.",
  "Always read `proposal.md` and the referenced requirement document before generating semantic artifacts.",
  "If the requirement document is missing, unreadable, remote, or ambiguous, stop and ask the user for readable content or explicit authorization; do not guess.",
  "Every generated requirement, test point, and test case must trace to requirement IDs and source evidence when available.",
  "Use `待确认` or clarification questions for unspecified behavior instead of fabricating business rules, roles, state transitions, limits, or SLA values.",
  "Generate concrete executable steps and observable expected results; avoid generic template wording such as 'execute operation' or '符合需求'.",
  "Run `testspec validate [name]` before export workflows and fix blocking validation errors before producing Excel or mind-map artifacts.",
] as const;

export interface AgentIntegration {
  id: AgentId;
  displayName: string;
  description: string;
  defaultSelected: boolean;
}

export const AGENT_INTEGRATIONS: AgentIntegration[] = [
  {
    id: "claude",
    displayName: "Claude Code",
    description: "Generate .claude slash commands such as /test:new.",
    defaultSelected: true,
  },
  {
    id: "qoder",
    displayName: "Qoder",
    description: "Generate .qoder command files for the /test:* workflow.",
    defaultSelected: false,
  },
  {
    id: "codex",
    displayName: "Codex",
    description: "Update AGENTS.md with Codex-friendly TestSpec workflow guidance.",
    defaultSelected: true,
  },
  {
    id: "generic",
    displayName: "Generic Agent guidance",
    description: "Update AGENTS.md with tool-agnostic TestSpec workflow guidance.",
    defaultSelected: false,
  },
];

export const DEFAULT_AGENT_IDS = AGENT_INTEGRATIONS.filter((agent) => agent.defaultSelected).map(
  (agent) => agent.id
);

export interface AgentSelectionItem {
  integration: AgentIntegration;
  selected: boolean;
}

export interface InitOptions {
  cwd?: string;
  agents?: string;
  force?: boolean;
  input?: NodeJS.ReadStream;
  output?: NodeJS.WriteStream;
}

export interface InitResult {
  selectedAgents: AgentId[];
  directories: string[];
  created: string[];
  refreshed: string[];
  preserved: string[];
}

interface WriteResult {
  status: "created" | "refreshed" | "preserved";
  path: string;
}

export function createAgentSelectionItems(
  defaultIds: readonly AgentId[] = DEFAULT_AGENT_IDS
): AgentSelectionItem[] {
  const defaults = new Set(defaultIds);
  return AGENT_INTEGRATIONS.map((integration) => ({
    integration,
    selected: defaults.has(integration.id),
  }));
}

export function toggleAgentSelection(
  items: readonly AgentSelectionItem[],
  index: number
): AgentSelectionItem[] {
  return items.map((item, itemIndex) =>
    itemIndex === index ? { ...item, selected: !item.selected } : { ...item }
  );
}

export function selectedAgentIds(items: readonly AgentSelectionItem[]): AgentId[] {
  return items.filter((item) => item.selected).map((item) => item.integration.id);
}

export function parseAgentSelection(value: string): AgentId[] {
  const normalized = value.trim().toLowerCase();

  if (normalized.length === 0) {
    throw new TestSpecError("--agents must include at least one agent id.");
  }

  if (normalized === "all") {
    return AGENT_INTEGRATIONS.map((agent) => agent.id);
  }

  const knownIds = new Set<AgentId>(AGENT_INTEGRATIONS.map((agent) => agent.id));
  const parsed: AgentId[] = [];

  for (const rawEntry of normalized.split(",")) {
    const entry = rawEntry.trim();
    if (entry.length === 0) {
      continue;
    }
    if (!knownIds.has(entry as AgentId)) {
      throw new TestSpecError(
        `Unknown agent '${entry}'. Supported agents: ${AGENT_INTEGRATIONS.map((agent) => agent.id).join(", ")}, all.`
      );
    }
    const agentId = entry as AgentId;
    if (!parsed.includes(agentId)) {
      parsed.push(agentId);
    }
  }

  if (parsed.length === 0) {
    throw new TestSpecError("--agents must include at least one supported agent id.");
  }

  return parsed;
}

export async function initializeTestSpec(options: InitOptions = {}): Promise<InitResult> {
  const cwd = options.cwd ?? process.cwd();
  const selectedAgents = await resolveAgentSelection(options);
  const result: InitResult = {
    selectedAgents,
    directories: [],
    created: [],
    refreshed: [],
    preserved: [],
  };

  const archiveDir = join(cwd, WORKSPACE_ROOT, CHANGES_DIR, ARCHIVE_DIR);
  await mkdir(archiveDir, { recursive: true });
  result.directories.push(
    join(WORKSPACE_ROOT, CHANGES_DIR),
    join(WORKSPACE_ROOT, CHANGES_DIR, ARCHIVE_DIR)
  );

  if (selectedAgents.includes("claude")) {
    await writeCommandFiles(cwd, ".claude", options.force === true, result);
  }

  if (selectedAgents.includes("qoder")) {
    await writeCommandFiles(cwd, ".qoder", options.force === true, result);
  }

  if (selectedAgents.includes("codex") || selectedAgents.includes("generic")) {
    const agentsResult = await writeAgentsFile(cwd, selectedAgents, options.force === true);
    collectWriteResult(result, agentsResult);
  }

  return result;
}

async function resolveAgentSelection(options: InitOptions): Promise<AgentId[]> {
  if (options.agents !== undefined) {
    return parseAgentSelection(options.agents);
  }

  const input = options.input ?? defaultInput;
  const output = options.output ?? defaultOutput;

  if (isInteractiveInput(input)) {
    return promptAgentSelection(input, output);
  }

  return [...DEFAULT_AGENT_IDS];
}

export async function promptAgentSelection(
  input: NodeJS.ReadStream = defaultInput,
  output: NodeJS.WriteStream = defaultOutput
): Promise<AgentId[]> {
  if (!isInteractiveInput(input)) {
    return [...DEFAULT_AGENT_IDS];
  }

  const readStream = input as ReadStream;
  const writeStream = output as WriteStream;
  const wasRaw = readStream.isRaw;
  let cursor = 0;
  let items = createAgentSelectionItems();

  function render(): void {
    writeStream.write("\x1B[2J\x1B[0f");
    writeStream.write("Select Agent integrations for TestSpec init\n");
    writeStream.write("Use ↑/↓ to move, Space to select, Enter to confirm.\n\n");
    for (const [index, item] of items.entries()) {
      const pointer = index === cursor ? "›" : " ";
      const check = item.selected ? "◉" : "○";
      writeStream.write(
        `${pointer} ${check} ${item.integration.displayName} - ${item.integration.description}\n`
      );
    }
  }

  readStream.setRawMode(true);
  readStream.resume();
  render();

  return new Promise((resolve, reject) => {
    const onData = (data: Buffer): void => {
      const key = data.toString("utf8");

      if (key.includes("")) {
        cleanup();
        reject(new TestSpecError("TestSpec init cancelled."));
        return;
      }

      if (key.includes("\r") || key.includes("\n")) {
        const selected = selectedAgentIds(items);
        cleanup();
        writeStream.write(`Selected: ${formatAgentNames(selected)}\n`);
        resolve(selected.length > 0 ? selected : [...DEFAULT_AGENT_IDS]);
        return;
      }

      if (key === " ") {
        items = toggleAgentSelection(items, cursor);
        render();
        return;
      }

      if (key === "\x1B[A") {
        cursor = cursor === 0 ? items.length - 1 : cursor - 1;
        render();
        return;
      }

      if (key === "\x1B[B") {
        cursor = cursor === items.length - 1 ? 0 : cursor + 1;
        render();
      }
    };

    function cleanup(): void {
      readStream.off("data", onData);
      readStream.setRawMode(wasRaw);
      if (readStream.listenerCount("data") === 0) {
        readStream.pause();
      }
      writeStream.write("\n");
    }

    readStream.on("data", onData);
  });
}

function isInteractiveInput(input: NodeJS.ReadStream): input is ReadStream {
  return input.isTTY === true && typeof (input as ReadStream).setRawMode === "function";
}

async function writeCommandFiles(
  cwd: string,
  rootDir: ".claude" | ".qoder",
  force: boolean,
  result: InitResult
): Promise<void> {
  for (const command of WORKFLOW_COMMANDS) {
    const outputPath = join(cwd, rootDir, "commands", "test", `${command.id}.md`);
    const writeResult = await writeGeneratedFile(outputPath, renderCommandFile(command), force);
    collectWriteResult(result, writeResult);
  }
}

async function writeGeneratedFile(
  path: string,
  content: string,
  force: boolean
): Promise<WriteResult> {
  await mkdir(dirname(path), { recursive: true });

  if (!(await pathExists(path))) {
    await writeFile(path, content);
    return { status: "created", path };
  }

  const existing = await readFile(path, "utf8");
  if (!force && !existing.includes(GENERATED_FILE_MARKER)) {
    return { status: "preserved", path };
  }

  await writeFile(path, content);
  return { status: "refreshed", path };
}

async function writeAgentsFile(
  cwd: string,
  selectedAgents: readonly AgentId[],
  force: boolean
): Promise<WriteResult> {
  const outputPath = join(cwd, "AGENTS.md");
  const section = renderAgentsSection(selectedAgents);

  if (!(await pathExists(outputPath))) {
    await writeFile(outputPath, `${section}\n`);
    return { status: "created", path: outputPath };
  }

  const existing = await readFile(outputPath, "utf8");
  const start = existing.indexOf(AGENTS_SECTION_START);
  const end = existing.indexOf(AGENTS_SECTION_END);

  if (start >= 0 && end > start) {
    if (!force) {
      return { status: "preserved", path: outputPath };
    }

    const before = existing.slice(0, start).trimEnd();
    const after = existing.slice(end + AGENTS_SECTION_END.length).trimStart();
    const nextContent = [before, section, after].filter((part) => part.length > 0).join("\n\n");
    await writeFile(outputPath, `${nextContent}\n`);
    return { status: "refreshed", path: outputPath };
  }

  const nextContent = [existing.trimEnd(), section].filter((part) => part.length > 0).join("\n\n");
  await writeFile(outputPath, `${nextContent}\n`);
  return { status: "refreshed", path: outputPath };
}

function renderCommandFile(command: WorkflowCommand): string {
  return [
    "---",
    `name: TestSpec ${titleCase(command.id)}`,
    `description: ${command.description}`,
    "category: TestSpec",
    "tags: [testspec, workflow, test]",
    "---",
    "",
    GENERATED_FILE_MARKER,
    "",
    `# ${command.slashCommand}`,
    "",
    `Treat \`${command.slashCommand}\` as the Agent workflow label \`${command.label}\` for TestSpec.`,
    "",
    ...agentWorkflowInstructions(command),
    "",
    "Provider-neutral generation rules:",
    "",
    ...PROVIDER_NEUTRAL_PROMPT_RULES.map((rule) => `- ${rule}`),
    "",
  ].join("\n");
}

function agentWorkflowInstructions(command: WorkflowCommand): string[] {
  if (command.id === "analysis") {
    return [
      "Agent workflow:",
      "",
      "1. Resolve the target change from the user's argument or the active `testspec/changes/<name>/` workspace.",
      "2. Read `proposal.md` and the requirement reference under `## 关联需求文档`.",
      "3. Read the local requirement document when available. If it cannot be read, ask the user for content or authorization before continuing.",
      "4. Generate `requirements-analysis.md` with requirement IDs, source evidence, business rules, boundaries, dependencies, risks, assumptions, and clarification questions.",
      `5. Deterministic fallback/template CLI command, if no semantic generation is possible: \`${command.backingCommand}\`.`,
      "6. Report the generated artifact path and any clarification questions.",
    ];
  }

  if (command.id === "points") {
    return [
      "Agent workflow:",
      "",
      "1. Read `proposal.md`, `requirements-analysis.md`, and available requirement evidence.",
      "2. Generate `specs/testpoints.md` with stable `TP-xxx` IDs, linked `REQ-xxx` IDs, scenario type, priority/risk, and source evidence.",
      "3. Cover positive, negative, boundary, exception, permission/security, state-flow, data-validation, and risk scenarios only where supported by the requirement evidence.",
      "4. Mark unsupported or unclear behavior as `待确认` instead of inventing coverage.",
      `5. Deterministic fallback/template CLI command, if no semantic generation is possible: \`${command.backingCommand}\`.`,
      "6. Report the generated artifact path and coverage gaps.",
    ];
  }

  if (command.id === "excel") {
    return [
      "Agent workflow:",
      "",
      "1. Read `proposal.md`, `requirements-analysis.md`, `specs/testpoints.md`, and available requirement evidence.",
      "2. Generate or update `artifacts/testcases.json` with concrete test data, executable steps, observable expected results, requirement/test-point/risk traceability, and `sourceRefs`.",
      "3. Run `testspec validate [name]` and fix blocking errors before export.",
      "4. Run the backing CLI export command:",
      "",
      "```bash",
      command.backingCommand,
      "```",
      "",
      "5. Report validation status and the exported workbook path.",
    ];
  }

  if (command.id === "validate") {
    return [
      "Run the backing CLI validation command with the user's arguments:",
      "",
      "```bash",
      command.backingCommand,
      "```",
      "",
      "Treat validation errors as blockers. Treat validation warnings as review items to discuss or fix.",
    ];
  }

  return [
    "Run the backing CLI command with the user's arguments:",
    "",
    "```bash",
    command.backingCommand,
    "```",
    "",
    "Guidelines:",
    "",
    "- Use the installed `testspec` CLI as the source of truth for deterministic workspace, export, report, and archive operations.",
    "- If required arguments are missing, ask the user before running the command.",
    "- Do not treat the `test:*` label as a shell command; it is an Agent workflow label.",
    "- Report the generated artifact paths after the command completes.",
  ];
}

function renderAgentsSection(selectedAgents: readonly AgentId[]): string {
  const agentNames = formatAgentNames(selectedAgents);
  const rows = WORKFLOW_COMMANDS.map(
    (command) =>
      `| \`${command.label}\` | \`${command.backingCommand}\` | ${agentBehaviorSummary(command)} |`
  );

  return [
    AGENTS_SECTION_START,
    "# TestSpec Agent Workflow",
    "",
    GENERATED_FILE_MARKER,
    "",
    `Configured integrations: ${agentNames}.`,
    "",
    "TestSpec uses agent-executed generation and CLI-managed validation/export. Claude Code, Codex, Qoder, or another coding agent should generate semantic artifacts from requirements; the `testspec` CLI remains provider-free and deterministic.",
    "",
    "Provider-neutral generation rules:",
    "",
    ...PROVIDER_NEUTRAL_PROMPT_RULES.map((rule) => `- ${rule}`),
    "",
    "Workflow labels and backing CLI commands:",
    "",
    "| Workflow label | Backing CLI command | Agent behavior |",
    "|---|---|---|",
    ...rows,
    "",
    "Recommended order:",
    "",
    "1. `test:new` creates `testspec/changes/<name>/proposal.md`.",
    "2. `test:analysis` creates grounded `requirements-analysis.md` from requirement evidence.",
    "3. `test:points` creates traceable `specs/testpoints.md`.",
    "4. `test:excel` creates concrete `artifacts/testcases.json`, runs `testspec validate`, and exports `artifacts/<name>_cases.xlsx`.",
    "5. `test:validate` can be run independently to check schema, traceability, and quality.",
    "6. `test:mind` creates `artifacts/<name>_cases.xmind` from the same structured cases.",
    "7. `test:report` creates `report.md` after Excel execution results are filled.",
    "8. `test:archive` moves the change to `testspec/changes/archive/<date>-<name>/`.",
    "",
    "Important: `test:*` entries are Agent workflow labels, not shell commands. Use `testspec <subcommand>` in the terminal.",
    AGENTS_SECTION_END,
  ].join("\n");
}

function agentBehaviorSummary(command: WorkflowCommand): string {
  if (command.id === "analysis") {
    return "Agent reads the requirement source and writes grounded `requirements-analysis.md`.";
  }
  if (command.id === "points") {
    return "Agent derives traceable `specs/testpoints.md` from analysis and source evidence.";
  }
  if (command.id === "excel") {
    return "Agent writes concrete `artifacts/testcases.json`, validates it, then exports Excel.";
  }
  if (command.id === "validate") {
    return "CLI validates schema, traceability, and quality of generated artifacts.";
  }
  return command.description;
}

function collectWriteResult(result: InitResult, writeResult: WriteResult): void {
  if (writeResult.status === "created") {
    result.created.push(writeResult.path);
  } else if (writeResult.status === "refreshed") {
    result.refreshed.push(writeResult.path);
  } else {
    result.preserved.push(writeResult.path);
  }
}

function formatAgentNames(agentIds: readonly AgentId[]): string {
  if (agentIds.length === 0) {
    return "none";
  }
  const names = agentIds.map((agentId) => {
    const integration = AGENT_INTEGRATIONS.find((agent) => agent.id === agentId);
    return integration?.displayName ?? agentId;
  });
  return names.join(", ");
}

function titleCase(value: string): string {
  return value.slice(0, 1).toUpperCase() + value.slice(1);
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}
