import { constants } from "node:fs";
import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { stdin as defaultInput, stdout as defaultOutput } from "node:process";
import type { ReadStream, WriteStream } from "node:tty";
import { TestSpecError } from "../core/errors.js";
import { ARCHIVE_DIR, CHANGES_DIR, WORKSPACE_ROOT } from "../workflow/workspace.js";

export const GENERATED_FILE_MARKER =
  "<!-- Generated by TestSpec. Keep this marker to allow `testspec init` to refresh this file. -->";
export const AGENTS_SECTION_START = "<!-- BEGIN TESTSPEC AGENT WORKFLOW -->";
export const AGENTS_SECTION_END = "<!-- END TESTSPEC AGENT WORKFLOW -->";

export const WORKFLOW_COMMANDS = [
  {
    id: "new",
    label: "test:new",
    slashCommand: "/test:new",
    backingCommand: "testspec new <name> --requirement <path>",
    description: "Create a test proposal workspace from a requirement document.",
  },
  {
    id: "analysis",
    label: "test:analysis",
    slashCommand: "/test:analysis",
    backingCommand: "testspec analysis [name]",
    description: "Decompose requirements into testable items, risks, and questions.",
  },
  {
    id: "points",
    label: "test:points",
    slashCommand: "/test:points",
    backingCommand: "testspec points [name]",
    description: "Generate core scenario test points for a test change.",
  },
  {
    id: "excel",
    label: "test:excel",
    slashCommand: "/test:excel",
    backingCommand: "testspec excel [name]",
    description: "Export executable Excel test cases.",
  },
  {
    id: "mind",
    label: "test:mind",
    slashCommand: "/test:mind",
    backingCommand: "testspec mind [name]",
    description: "Export mind-map style test cases for review.",
  },
  {
    id: "report",
    label: "test:report",
    slashCommand: "/test:report",
    backingCommand: "testspec report [name]",
    description: "Generate execution statistics from Excel results.",
  },
  {
    id: "archive",
    label: "test:archive",
    slashCommand: "/test:archive",
    backingCommand: "testspec archive [name]",
    description: "Archive the full test artifact chain for traceability.",
  },
] as const;

export type WorkflowCommand = (typeof WORKFLOW_COMMANDS)[number];
export type AgentId = "claude" | "qoder" | "codex" | "generic";

export interface AgentIntegration {
  id: AgentId;
  displayName: string;
  description: string;
  defaultSelected: boolean;
}

export const AGENT_INTEGRATIONS: AgentIntegration[] = [
  {
    id: "claude",
    displayName: "Claude Code",
    description: "Generate .claude slash commands such as /test:new.",
    defaultSelected: true,
  },
  {
    id: "qoder",
    displayName: "Qoder",
    description: "Generate .qoder command files for the /test:* workflow.",
    defaultSelected: false,
  },
  {
    id: "codex",
    displayName: "Codex",
    description: "Update AGENTS.md with Codex-friendly TestSpec workflow guidance.",
    defaultSelected: true,
  },
  {
    id: "generic",
    displayName: "Generic Agent guidance",
    description: "Update AGENTS.md with tool-agnostic TestSpec workflow guidance.",
    defaultSelected: false,
  },
];

export const DEFAULT_AGENT_IDS = AGENT_INTEGRATIONS.filter((agent) => agent.defaultSelected).map(
  (agent) => agent.id
);

export interface AgentSelectionItem {
  integration: AgentIntegration;
  selected: boolean;
}

export interface InitOptions {
  cwd?: string;
  agents?: string;
  force?: boolean;
  input?: NodeJS.ReadStream;
  output?: NodeJS.WriteStream;
}

export interface InitResult {
  selectedAgents: AgentId[];
  directories: string[];
  created: string[];
  refreshed: string[];
  preserved: string[];
}

interface WriteResult {
  status: "created" | "refreshed" | "preserved";
  path: string;
}

export function createAgentSelectionItems(
  defaultIds: readonly AgentId[] = DEFAULT_AGENT_IDS
): AgentSelectionItem[] {
  const defaults = new Set(defaultIds);
  return AGENT_INTEGRATIONS.map((integration) => ({
    integration,
    selected: defaults.has(integration.id),
  }));
}

export function toggleAgentSelection(
  items: readonly AgentSelectionItem[],
  index: number
): AgentSelectionItem[] {
  return items.map((item, itemIndex) =>
    itemIndex === index ? { ...item, selected: !item.selected } : { ...item }
  );
}

export function selectedAgentIds(items: readonly AgentSelectionItem[]): AgentId[] {
  return items.filter((item) => item.selected).map((item) => item.integration.id);
}

export function parseAgentSelection(value: string): AgentId[] {
  const normalized = value.trim().toLowerCase();

  if (normalized.length === 0) {
    throw new TestSpecError("--agents must include at least one agent id.");
  }

  if (normalized === "all") {
    return AGENT_INTEGRATIONS.map((agent) => agent.id);
  }

  const knownIds = new Set<AgentId>(AGENT_INTEGRATIONS.map((agent) => agent.id));
  const parsed: AgentId[] = [];

  for (const rawEntry of normalized.split(",")) {
    const entry = rawEntry.trim();
    if (entry.length === 0) {
      continue;
    }
    if (!knownIds.has(entry as AgentId)) {
      throw new TestSpecError(
        `Unknown agent '${entry}'. Supported agents: ${AGENT_INTEGRATIONS.map((agent) => agent.id).join(", ")}, all.`
      );
    }
    const agentId = entry as AgentId;
    if (!parsed.includes(agentId)) {
      parsed.push(agentId);
    }
  }

  if (parsed.length === 0) {
    throw new TestSpecError("--agents must include at least one supported agent id.");
  }

  return parsed;
}

export async function initializeTestSpec(options: InitOptions = {}): Promise<InitResult> {
  const cwd = options.cwd ?? process.cwd();
  const selectedAgents = await resolveAgentSelection(options);
  const result: InitResult = {
    selectedAgents,
    directories: [],
    created: [],
    refreshed: [],
    preserved: [],
  };

  const archiveDir = join(cwd, WORKSPACE_ROOT, CHANGES_DIR, ARCHIVE_DIR);
  await mkdir(archiveDir, { recursive: true });
  result.directories.push(
    join(WORKSPACE_ROOT, CHANGES_DIR),
    join(WORKSPACE_ROOT, CHANGES_DIR, ARCHIVE_DIR)
  );

  if (selectedAgents.includes("claude")) {
    await writeCommandFiles(cwd, ".claude", options.force === true, result);
  }

  if (selectedAgents.includes("qoder")) {
    await writeCommandFiles(cwd, ".qoder", options.force === true, result);
  }

  if (selectedAgents.includes("codex") || selectedAgents.includes("generic")) {
    const agentsResult = await writeAgentsFile(cwd, selectedAgents, options.force === true);
    collectWriteResult(result, agentsResult);
  }

  return result;
}

async function resolveAgentSelection(options: InitOptions): Promise<AgentId[]> {
  if (options.agents !== undefined) {
    return parseAgentSelection(options.agents);
  }

  const input = options.input ?? defaultInput;
  const output = options.output ?? defaultOutput;

  if (isInteractiveInput(input)) {
    return promptAgentSelection(input, output);
  }

  return [...DEFAULT_AGENT_IDS];
}

export async function promptAgentSelection(
  input: NodeJS.ReadStream = defaultInput,
  output: NodeJS.WriteStream = defaultOutput
): Promise<AgentId[]> {
  if (!isInteractiveInput(input)) {
    return [...DEFAULT_AGENT_IDS];
  }

  const readStream = input as ReadStream;
  const writeStream = output as WriteStream;
  const wasRaw = readStream.isRaw;
  let cursor = 0;
  let items = createAgentSelectionItems();

  function render(): void {
    writeStream.write("\x1B[2J\x1B[0f");
    writeStream.write("Select Agent integrations for TestSpec init\n");
    writeStream.write("Use ↑/↓ to move, Space to select, Enter to confirm.\n\n");
    for (const [index, item] of items.entries()) {
      const pointer = index === cursor ? "›" : " ";
      const check = item.selected ? "◉" : "○";
      writeStream.write(
        `${pointer} ${check} ${item.integration.displayName} - ${item.integration.description}\n`
      );
    }
  }

  readStream.setRawMode(true);
  readStream.resume();
  render();

  return new Promise((resolve, reject) => {
    const onData = (data: Buffer): void => {
      const key = data.toString("utf8");

      if (key.includes("")) {
        cleanup();
        reject(new TestSpecError("TestSpec init cancelled."));
        return;
      }

      if (key.includes("\r") || key.includes("\n")) {
        const selected = selectedAgentIds(items);
        cleanup();
        writeStream.write(`Selected: ${formatAgentNames(selected)}\n`);
        resolve(selected.length > 0 ? selected : [...DEFAULT_AGENT_IDS]);
        return;
      }

      if (key === " ") {
        items = toggleAgentSelection(items, cursor);
        render();
        return;
      }

      if (key === "\x1B[A") {
        cursor = cursor === 0 ? items.length - 1 : cursor - 1;
        render();
        return;
      }

      if (key === "\x1B[B") {
        cursor = cursor === items.length - 1 ? 0 : cursor + 1;
        render();
      }
    };

    function cleanup(): void {
      readStream.off("data", onData);
      readStream.setRawMode(wasRaw);
      if (readStream.listenerCount("data") === 0) {
        readStream.pause();
      }
      writeStream.write("\n");
    }

    readStream.on("data", onData);
  });
}

function isInteractiveInput(input: NodeJS.ReadStream): input is ReadStream {
  return input.isTTY === true && typeof (input as ReadStream).setRawMode === "function";
}

async function writeCommandFiles(
  cwd: string,
  rootDir: ".claude" | ".qoder",
  force: boolean,
  result: InitResult
): Promise<void> {
  for (const command of WORKFLOW_COMMANDS) {
    const outputPath = join(cwd, rootDir, "commands", "test", `${command.id}.md`);
    const writeResult = await writeGeneratedFile(outputPath, renderCommandFile(command), force);
    collectWriteResult(result, writeResult);
  }
}

async function writeGeneratedFile(
  path: string,
  content: string,
  force: boolean
): Promise<WriteResult> {
  await mkdir(dirname(path), { recursive: true });

  if (!(await pathExists(path))) {
    await writeFile(path, content);
    return { status: "created", path };
  }

  const existing = await readFile(path, "utf8");
  if (!force && !existing.includes(GENERATED_FILE_MARKER)) {
    return { status: "preserved", path };
  }

  await writeFile(path, content);
  return { status: "refreshed", path };
}

async function writeAgentsFile(
  cwd: string,
  selectedAgents: readonly AgentId[],
  force: boolean
): Promise<WriteResult> {
  const outputPath = join(cwd, "AGENTS.md");
  const section = renderAgentsSection(selectedAgents);

  if (!(await pathExists(outputPath))) {
    await writeFile(outputPath, `${section}\n`);
    return { status: "created", path: outputPath };
  }

  const existing = await readFile(outputPath, "utf8");
  const start = existing.indexOf(AGENTS_SECTION_START);
  const end = existing.indexOf(AGENTS_SECTION_END);

  if (start >= 0 && end > start) {
    if (!force) {
      return { status: "preserved", path: outputPath };
    }

    const before = existing.slice(0, start).trimEnd();
    const after = existing.slice(end + AGENTS_SECTION_END.length).trimStart();
    const nextContent = [before, section, after].filter((part) => part.length > 0).join("\n\n");
    await writeFile(outputPath, `${nextContent}\n`);
    return { status: "refreshed", path: outputPath };
  }

  const nextContent = [existing.trimEnd(), section].filter((part) => part.length > 0).join("\n\n");
  await writeFile(outputPath, `${nextContent}\n`);
  return { status: "refreshed", path: outputPath };
}

function renderCommandFile(command: WorkflowCommand): string {
  return [
    "---",
    `name: TestSpec ${titleCase(command.id)}`,
    `description: ${command.description}`,
    "category: TestSpec",
    "tags: [testspec, workflow, test]",
    "---",
    "",
    GENERATED_FILE_MARKER,
    "",
    `# ${command.slashCommand}`,
    "",
    `Treat \`${command.slashCommand}\` as the Agent workflow label \`${command.label}\` for TestSpec.`,
    "",
    "Run the backing CLI command with the user's arguments:",
    "",
    "```bash",
    command.backingCommand,
    "```",
    "",
    "Guidelines:",
    "",
    "- Use the installed `testspec` CLI as the source of truth.",
    "- If required arguments are missing, ask the user before running the command.",
    "- Do not treat the `test:*` label as a shell command; it is an Agent workflow label.",
    "- Report the generated artifact paths after the command completes.",
    "",
  ].join("\n");
}

function renderAgentsSection(selectedAgents: readonly AgentId[]): string {
  const agentNames = formatAgentNames(selectedAgents);
  const rows = WORKFLOW_COMMANDS.map(
    (command) => `| \`${command.label}\` | \`${command.backingCommand}\` | ${command.description} |`
  );

  return [
    AGENTS_SECTION_START,
    "# TestSpec Agent Workflow",
    "",
    GENERATED_FILE_MARKER,
    "",
    `Configured integrations: ${agentNames}.`,
    "",
    "When the user asks for a TestSpec workflow label, run the backing CLI command:",
    "",
    "| Workflow label | Backing CLI command | Purpose |",
    "|---|---|---|",
    ...rows,
    "",
    "Recommended order:",
    "",
    "1. `test:new` creates `testspec/changes/<name>/proposal.md`.",
    "2. `test:analysis` creates `requirements-analysis.md`.",
    "3. `test:points` creates `specs/testpoints.md`.",
    "4. `test:excel` creates `artifacts/<name>_cases.xlsx`.",
    "5. `test:mind` creates `artifacts/<name>_cases.xmind`.",
    "6. `test:report` creates `report.md` after Excel execution results are filled.",
    "7. `test:archive` moves the change to `testspec/changes/archive/<date>-<name>/`.",
    "",
    "Important: `test:*` entries are Agent workflow labels, not shell commands. Use `testspec <subcommand>` in the terminal.",
    AGENTS_SECTION_END,
  ].join("\n");
}

function collectWriteResult(result: InitResult, writeResult: WriteResult): void {
  if (writeResult.status === "created") {
    result.created.push(writeResult.path);
  } else if (writeResult.status === "refreshed") {
    result.refreshed.push(writeResult.path);
  } else {
    result.preserved.push(writeResult.path);
  }
}

function formatAgentNames(agentIds: readonly AgentId[]): string {
  if (agentIds.length === 0) {
    return "none";
  }
  const names = agentIds.map((agentId) => {
    const integration = AGENT_INTEGRATIONS.find((agent) => agent.id === agentId);
    return integration?.displayName ?? agentId;
  });
  return names.join(", ");
}

function titleCase(value: string): string {
  return value.slice(0, 1).toUpperCase() + value.slice(1);
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}
